#!/bin/bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

SRC=$DIR/bhl.cs
EXE=$DIR/bhlb.exe
export MONO_PATH="$DIR/deps/:$MONO_PATH" 

if [ $EXE -ot $SRC ]; then 
  mcs $SRC -debug -r:$DIR/deps/mono_opts.dll -out:$EXE
fi

if [[ -z "${BHL_DEBUG}" ]]; then
mono --debug $EXE $*
else
mono --debug --debugger-agent=transport=dt_socket,server=y,address=127.0.0.1:55556 $EXE $*
fi
