#!/bin/bash

ANTLR=4.13.1
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
DOWNLOAD_URL="https://www.antlr.org/download/antlr-$ANTLR-complete.jar"
JAR=$DIR/antlr-$ANTLR-complete.jar

if [ ! -f "$JAR" ]; then
    echo "ANTLR jar not found. Downloading..."
    wget "$DOWNLOAD_URL" -O "$JAR"
    
    if [ $? -eq 0 ]; then
        echo "Download completed successfully."
    else
        echo "Download failed. Please check your internet connection and the URL."
        exit 1
    fi
fi

export CLASSPATH=".:$JAR:$CLASSPATH"
java -Xmx500M -cp "$JAR:$CLASSPATH" $*
