//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from bhl.g by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IbhlListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class bhlBaseListener : IbhlListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] bhlParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] bhlParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.progblock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgblock([NotNull] bhlParser.ProgblockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.progblock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgblock([NotNull] bhlParser.ProgblockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.imports"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImports([NotNull] bhlParser.ImportsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.imports"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImports([NotNull] bhlParser.ImportsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.mimport"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMimport([NotNull] bhlParser.MimportContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.mimport"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMimport([NotNull] bhlParser.MimportContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.decls"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDecls([NotNull] bhlParser.DeclsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.decls"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDecls([NotNull] bhlParser.DeclsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDecl([NotNull] bhlParser.DeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDecl([NotNull] bhlParser.DeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.dotName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDotName([NotNull] bhlParser.DotNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.dotName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDotName([NotNull] bhlParser.DotNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.nsName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNsName([NotNull] bhlParser.NsNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.nsName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNsName([NotNull] bhlParser.NsNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] bhlParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] bhlParser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.mapType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMapType([NotNull] bhlParser.MapTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.mapType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMapType([NotNull] bhlParser.MapTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.exps"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExps([NotNull] bhlParser.ExpsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.exps"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExps([NotNull] bhlParser.ExpsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.returnVal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnVal([NotNull] bhlParser.ReturnValContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.returnVal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnVal([NotNull] bhlParser.ReturnValContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpJsonArr</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpJsonArr([NotNull] bhlParser.ExpJsonArrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpJsonArr</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpJsonArr([NotNull] bhlParser.ExpJsonArrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpTypeof</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpTypeof([NotNull] bhlParser.ExpTypeofContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpTypeof</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpTypeof([NotNull] bhlParser.ExpTypeofContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpIs</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpIs([NotNull] bhlParser.ExpIsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpIs</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpIs([NotNull] bhlParser.ExpIsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpOr</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpOr([NotNull] bhlParser.ExpOrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpOr</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpOr([NotNull] bhlParser.ExpOrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpLiteralFalse</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpLiteralFalse([NotNull] bhlParser.ExpLiteralFalseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpLiteralFalse</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpLiteralFalse([NotNull] bhlParser.ExpLiteralFalseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpLiteralNum</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpLiteralNum([NotNull] bhlParser.ExpLiteralNumContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpLiteralNum</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpLiteralNum([NotNull] bhlParser.ExpLiteralNumContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpCall</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpCall([NotNull] bhlParser.ExpCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpCall</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpCall([NotNull] bhlParser.ExpCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpMulDivMod</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpMulDivMod([NotNull] bhlParser.ExpMulDivModContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpMulDivMod</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpMulDivMod([NotNull] bhlParser.ExpMulDivModContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpCompare</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpCompare([NotNull] bhlParser.ExpCompareContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpCompare</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpCompare([NotNull] bhlParser.ExpCompareContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpAs</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpAs([NotNull] bhlParser.ExpAsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpAs</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpAs([NotNull] bhlParser.ExpAsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpLiteralStr</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpLiteralStr([NotNull] bhlParser.ExpLiteralStrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpLiteralStr</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpLiteralStr([NotNull] bhlParser.ExpLiteralStrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpLiteralTrue</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpLiteralTrue([NotNull] bhlParser.ExpLiteralTrueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpLiteralTrue</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpLiteralTrue([NotNull] bhlParser.ExpLiteralTrueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpJsonObj</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpJsonObj([NotNull] bhlParser.ExpJsonObjContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpJsonObj</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpJsonObj([NotNull] bhlParser.ExpJsonObjContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpUnary</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpUnary([NotNull] bhlParser.ExpUnaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpUnary</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpUnary([NotNull] bhlParser.ExpUnaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpNew</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpNew([NotNull] bhlParser.ExpNewContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpNew</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpNew([NotNull] bhlParser.ExpNewContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpAddSub</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpAddSub([NotNull] bhlParser.ExpAddSubContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpAddSub</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpAddSub([NotNull] bhlParser.ExpAddSubContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpBitAnd</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpBitAnd([NotNull] bhlParser.ExpBitAndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpBitAnd</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpBitAnd([NotNull] bhlParser.ExpBitAndContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpLiteralNull</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpLiteralNull([NotNull] bhlParser.ExpLiteralNullContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpLiteralNull</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpLiteralNull([NotNull] bhlParser.ExpLiteralNullContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpTypeCast</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpTypeCast([NotNull] bhlParser.ExpTypeCastContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpTypeCast</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpTypeCast([NotNull] bhlParser.ExpTypeCastContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpTernaryIf</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpTernaryIf([NotNull] bhlParser.ExpTernaryIfContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpTernaryIf</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpTernaryIf([NotNull] bhlParser.ExpTernaryIfContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpLambda</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpLambda([NotNull] bhlParser.ExpLambdaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpLambda</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpLambda([NotNull] bhlParser.ExpLambdaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpAnd</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpAnd([NotNull] bhlParser.ExpAndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpAnd</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpAnd([NotNull] bhlParser.ExpAndContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpBitOr</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpBitOr([NotNull] bhlParser.ExpBitOrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpBitOr</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpBitOr([NotNull] bhlParser.ExpBitOrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpParen</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpParen([NotNull] bhlParser.ExpParenContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpParen</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpParen([NotNull] bhlParser.ExpParenContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.ternaryIfExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTernaryIfExp([NotNull] bhlParser.TernaryIfExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.ternaryIfExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTernaryIfExp([NotNull] bhlParser.TernaryIfExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.newExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNewExp([NotNull] bhlParser.NewExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.newExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNewExp([NotNull] bhlParser.NewExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.foreachExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForeachExp([NotNull] bhlParser.ForeachExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.foreachExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForeachExp([NotNull] bhlParser.ForeachExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.forStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForStmt([NotNull] bhlParser.ForStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.forStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForStmt([NotNull] bhlParser.ForStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.forStmts"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForStmts([NotNull] bhlParser.ForStmtsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.forStmts"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForStmts([NotNull] bhlParser.ForStmtsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.forPre"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForPre([NotNull] bhlParser.ForPreContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.forPre"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForPre([NotNull] bhlParser.ForPreContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.forCond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForCond([NotNull] bhlParser.ForCondContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.forCond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForCond([NotNull] bhlParser.ForCondContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.forPostIter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForPostIter([NotNull] bhlParser.ForPostIterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.forPostIter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForPostIter([NotNull] bhlParser.ForPostIterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.forExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForExp([NotNull] bhlParser.ForExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.forExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForExp([NotNull] bhlParser.ForExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.varDeclareAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarDeclareAssign([NotNull] bhlParser.VarDeclareAssignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.varDeclareAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarDeclareAssign([NotNull] bhlParser.VarDeclareAssignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.callPostIncDec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCallPostIncDec([NotNull] bhlParser.CallPostIncDecContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.callPostIncDec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCallPostIncDec([NotNull] bhlParser.CallPostIncDecContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.incrementOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncrementOperator([NotNull] bhlParser.IncrementOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.incrementOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncrementOperator([NotNull] bhlParser.IncrementOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.decrementOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDecrementOperator([NotNull] bhlParser.DecrementOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.decrementOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDecrementOperator([NotNull] bhlParser.DecrementOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.varsDeclareAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarsDeclareAssign([NotNull] bhlParser.VarsDeclareAssignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.varsDeclareAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarsDeclareAssign([NotNull] bhlParser.VarsDeclareAssignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>LambdaCall</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLambdaCall([NotNull] bhlParser.LambdaCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>LambdaCall</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLambdaCall([NotNull] bhlParser.LambdaCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>DeclAssign</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclAssign([NotNull] bhlParser.DeclAssignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>DeclAssign</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclAssign([NotNull] bhlParser.DeclAssignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>VarDecl</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarDecl([NotNull] bhlParser.VarDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>VarDecl</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarDecl([NotNull] bhlParser.VarDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>VarPostOpAssign</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarPostOpAssign([NotNull] bhlParser.VarPostOpAssignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>VarPostOpAssign</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarPostOpAssign([NotNull] bhlParser.VarPostOpAssignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>VarPostIncDec</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarPostIncDec([NotNull] bhlParser.VarPostIncDecContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>VarPostIncDec</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarPostIncDec([NotNull] bhlParser.VarPostIncDecContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>SymbCall</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSymbCall([NotNull] bhlParser.SymbCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>SymbCall</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSymbCall([NotNull] bhlParser.SymbCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>If</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf([NotNull] bhlParser.IfContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>If</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf([NotNull] bhlParser.IfContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>While</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhile([NotNull] bhlParser.WhileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>While</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhile([NotNull] bhlParser.WhileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>DoWhile</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDoWhile([NotNull] bhlParser.DoWhileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>DoWhile</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDoWhile([NotNull] bhlParser.DoWhileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>For</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFor([NotNull] bhlParser.ForContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>For</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFor([NotNull] bhlParser.ForContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Foreach</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForeach([NotNull] bhlParser.ForeachContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Foreach</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForeach([NotNull] bhlParser.ForeachContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Yield</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterYield([NotNull] bhlParser.YieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Yield</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitYield([NotNull] bhlParser.YieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>YieldWhile</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterYieldWhile([NotNull] bhlParser.YieldWhileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>YieldWhile</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitYieldWhile([NotNull] bhlParser.YieldWhileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Break</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBreak([NotNull] bhlParser.BreakContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Break</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBreak([NotNull] bhlParser.BreakContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Continue</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContinue([NotNull] bhlParser.ContinueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Continue</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContinue([NotNull] bhlParser.ContinueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Return</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturn([NotNull] bhlParser.ReturnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Return</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturn([NotNull] bhlParser.ReturnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Paral</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParal([NotNull] bhlParser.ParalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Paral</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParal([NotNull] bhlParser.ParalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ParalAll</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParalAll([NotNull] bhlParser.ParalAllContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ParalAll</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParalAll([NotNull] bhlParser.ParalAllContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Defer</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefer([NotNull] bhlParser.DeferContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Defer</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefer([NotNull] bhlParser.DeferContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>BlockNested</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlockNested([NotNull] bhlParser.BlockNestedContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>BlockNested</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlockNested([NotNull] bhlParser.BlockNestedContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.mainIf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMainIf([NotNull] bhlParser.MainIfContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.mainIf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMainIf([NotNull] bhlParser.MainIfContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.elseIf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseIf([NotNull] bhlParser.ElseIfContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.elseIf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseIf([NotNull] bhlParser.ElseIfContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.else"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElse([NotNull] bhlParser.ElseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.else"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElse([NotNull] bhlParser.ElseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.callExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCallExp([NotNull] bhlParser.CallExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.callExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCallExp([NotNull] bhlParser.CallExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.chainExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChainExp([NotNull] bhlParser.ChainExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.chainExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChainExp([NotNull] bhlParser.ChainExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.funcCallChain"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncCallChain([NotNull] bhlParser.FuncCallChainContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.funcCallChain"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncCallChain([NotNull] bhlParser.FuncCallChainContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.typeof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeof([NotNull] bhlParser.TypeofContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.typeof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeof([NotNull] bhlParser.TypeofContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.arrAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrAccess([NotNull] bhlParser.ArrAccessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.arrAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrAccess([NotNull] bhlParser.ArrAccessContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.memberAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMemberAccess([NotNull] bhlParser.MemberAccessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.memberAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMemberAccess([NotNull] bhlParser.MemberAccessContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.callArgs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCallArgs([NotNull] bhlParser.CallArgsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.callArgs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCallArgs([NotNull] bhlParser.CallArgsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.callArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCallArg([NotNull] bhlParser.CallArgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.callArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCallArg([NotNull] bhlParser.CallArgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] bhlParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] bhlParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.extensions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExtensions([NotNull] bhlParser.ExtensionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.extensions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExtensions([NotNull] bhlParser.ExtensionsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.nsDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNsDecl([NotNull] bhlParser.NsDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.nsDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNsDecl([NotNull] bhlParser.NsDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.classDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassDecl([NotNull] bhlParser.ClassDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.classDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassDecl([NotNull] bhlParser.ClassDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.classBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassBlock([NotNull] bhlParser.ClassBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.classBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassBlock([NotNull] bhlParser.ClassBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.classMembers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassMembers([NotNull] bhlParser.ClassMembersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.classMembers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassMembers([NotNull] bhlParser.ClassMembersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.fldAttribs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFldAttribs([NotNull] bhlParser.FldAttribsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.fldAttribs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFldAttribs([NotNull] bhlParser.FldAttribsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.fldDeclare"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFldDeclare([NotNull] bhlParser.FldDeclareContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.fldDeclare"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFldDeclare([NotNull] bhlParser.FldDeclareContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.classMember"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassMember([NotNull] bhlParser.ClassMemberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.classMember"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassMember([NotNull] bhlParser.ClassMemberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.interfaceDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterfaceDecl([NotNull] bhlParser.InterfaceDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.interfaceDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterfaceDecl([NotNull] bhlParser.InterfaceDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.interfaceBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterfaceBlock([NotNull] bhlParser.InterfaceBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.interfaceBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterfaceBlock([NotNull] bhlParser.InterfaceBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.interfaceMembers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterfaceMembers([NotNull] bhlParser.InterfaceMembersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.interfaceMembers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterfaceMembers([NotNull] bhlParser.InterfaceMembersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.interfaceMember"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterfaceMember([NotNull] bhlParser.InterfaceMemberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.interfaceMember"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterfaceMember([NotNull] bhlParser.InterfaceMemberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.enumDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumDecl([NotNull] bhlParser.EnumDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.enumDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumDecl([NotNull] bhlParser.EnumDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.enumBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumBlock([NotNull] bhlParser.EnumBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.enumBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumBlock([NotNull] bhlParser.EnumBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.enumMember"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumMember([NotNull] bhlParser.EnumMemberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.enumMember"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumMember([NotNull] bhlParser.EnumMemberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.virtualFlag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVirtualFlag([NotNull] bhlParser.VirtualFlagContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.virtualFlag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVirtualFlag([NotNull] bhlParser.VirtualFlagContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.overrideFlag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOverrideFlag([NotNull] bhlParser.OverrideFlagContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.overrideFlag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOverrideFlag([NotNull] bhlParser.OverrideFlagContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.staticFlag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStaticFlag([NotNull] bhlParser.StaticFlagContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.staticFlag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStaticFlag([NotNull] bhlParser.StaticFlagContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.funcAttribs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncAttribs([NotNull] bhlParser.FuncAttribsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.funcAttribs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncAttribs([NotNull] bhlParser.FuncAttribsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.funcDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncDecl([NotNull] bhlParser.FuncDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.funcDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncDecl([NotNull] bhlParser.FuncDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.funcType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncType([NotNull] bhlParser.FuncTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.funcType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncType([NotNull] bhlParser.FuncTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.funcBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncBlock([NotNull] bhlParser.FuncBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.funcBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncBlock([NotNull] bhlParser.FuncBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.interfaceFuncDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterfaceFuncDecl([NotNull] bhlParser.InterfaceFuncDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.interfaceFuncDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterfaceFuncDecl([NotNull] bhlParser.InterfaceFuncDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.funcLambda"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncLambda([NotNull] bhlParser.FuncLambdaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.funcLambda"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncLambda([NotNull] bhlParser.FuncLambdaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.refType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRefType([NotNull] bhlParser.RefTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.refType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRefType([NotNull] bhlParser.RefTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.retType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRetType([NotNull] bhlParser.RetTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.retType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRetType([NotNull] bhlParser.RetTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.types"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypes([NotNull] bhlParser.TypesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.types"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypes([NotNull] bhlParser.TypesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.funcParams"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncParams([NotNull] bhlParser.FuncParamsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.funcParams"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncParams([NotNull] bhlParser.FuncParamsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.funcParamDeclare"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncParamDeclare([NotNull] bhlParser.FuncParamDeclareContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.funcParamDeclare"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncParamDeclare([NotNull] bhlParser.FuncParamDeclareContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.varsDeclare"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarsDeclare([NotNull] bhlParser.VarsDeclareContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.varsDeclare"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarsDeclare([NotNull] bhlParser.VarsDeclareContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.varDeclare"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarDeclare([NotNull] bhlParser.VarDeclareContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.varDeclare"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarDeclare([NotNull] bhlParser.VarDeclareContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.varOrDeclare"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarOrDeclare([NotNull] bhlParser.VarOrDeclareContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.varOrDeclare"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarOrDeclare([NotNull] bhlParser.VarOrDeclareContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.varOrDeclares"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarOrDeclares([NotNull] bhlParser.VarOrDeclaresContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.varOrDeclares"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarOrDeclares([NotNull] bhlParser.VarOrDeclaresContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.varsDeclareOrCallExps"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarsDeclareOrCallExps([NotNull] bhlParser.VarsDeclareOrCallExpsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.varsDeclareOrCallExps"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarsDeclareOrCallExps([NotNull] bhlParser.VarsDeclareOrCallExpsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.varDeclareOrCallExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarDeclareOrCallExp([NotNull] bhlParser.VarDeclareOrCallExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.varDeclareOrCallExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarDeclareOrCallExp([NotNull] bhlParser.VarDeclareOrCallExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.assignExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignExp([NotNull] bhlParser.AssignExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.assignExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignExp([NotNull] bhlParser.AssignExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.operatorOr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorOr([NotNull] bhlParser.OperatorOrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.operatorOr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorOr([NotNull] bhlParser.OperatorOrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.operatorAnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorAnd([NotNull] bhlParser.OperatorAndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.operatorAnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorAnd([NotNull] bhlParser.OperatorAndContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.operatorBitOr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorBitOr([NotNull] bhlParser.OperatorBitOrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.operatorBitOr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorBitOr([NotNull] bhlParser.OperatorBitOrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.operatorBitAnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorBitAnd([NotNull] bhlParser.OperatorBitAndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.operatorBitAnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorBitAnd([NotNull] bhlParser.OperatorBitAndContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.operatorPostOpAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorPostOpAssign([NotNull] bhlParser.OperatorPostOpAssignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.operatorPostOpAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorPostOpAssign([NotNull] bhlParser.OperatorPostOpAssignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.operatorComparison"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorComparison([NotNull] bhlParser.OperatorComparisonContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.operatorComparison"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorComparison([NotNull] bhlParser.OperatorComparisonContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.operatorAddSub"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorAddSub([NotNull] bhlParser.OperatorAddSubContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.operatorAddSub"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorAddSub([NotNull] bhlParser.OperatorAddSubContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.operatorMulDivMod"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorMulDivMod([NotNull] bhlParser.OperatorMulDivModContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.operatorMulDivMod"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorMulDivMod([NotNull] bhlParser.OperatorMulDivModContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.operatorUnary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorUnary([NotNull] bhlParser.OperatorUnaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.operatorUnary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorUnary([NotNull] bhlParser.OperatorUnaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.isRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIsRef([NotNull] bhlParser.IsRefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.isRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIsRef([NotNull] bhlParser.IsRefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] bhlParser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] bhlParser.NumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString([NotNull] bhlParser.StringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString([NotNull] bhlParser.StringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.jsonObject"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJsonObject([NotNull] bhlParser.JsonObjectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.jsonObject"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJsonObject([NotNull] bhlParser.JsonObjectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.jsonEmptyObj"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJsonEmptyObj([NotNull] bhlParser.JsonEmptyObjContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.jsonEmptyObj"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJsonEmptyObj([NotNull] bhlParser.JsonEmptyObjContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.jsonPair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJsonPair([NotNull] bhlParser.JsonPairContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.jsonPair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJsonPair([NotNull] bhlParser.JsonPairContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.jsonArray"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJsonArray([NotNull] bhlParser.JsonArrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.jsonArray"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJsonArray([NotNull] bhlParser.JsonArrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.jsonEmptyArr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJsonEmptyArr([NotNull] bhlParser.JsonEmptyArrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.jsonEmptyArr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJsonEmptyArr([NotNull] bhlParser.JsonEmptyArrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.jsonValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJsonValue([NotNull] bhlParser.JsonValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.jsonValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJsonValue([NotNull] bhlParser.JsonValueContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
