//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from bhl.g by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="bhlParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IbhlListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] bhlParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] bhlParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.progblock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgblock([NotNull] bhlParser.ProgblockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.progblock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgblock([NotNull] bhlParser.ProgblockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.imports"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImports([NotNull] bhlParser.ImportsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.imports"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImports([NotNull] bhlParser.ImportsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.mimport"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMimport([NotNull] bhlParser.MimportContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.mimport"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMimport([NotNull] bhlParser.MimportContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.decls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDecls([NotNull] bhlParser.DeclsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.decls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDecls([NotNull] bhlParser.DeclsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDecl([NotNull] bhlParser.DeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDecl([NotNull] bhlParser.DeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.dotName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDotName([NotNull] bhlParser.DotNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.dotName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDotName([NotNull] bhlParser.DotNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.nsName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNsName([NotNull] bhlParser.NsNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.nsName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNsName([NotNull] bhlParser.NsNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] bhlParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] bhlParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.mapType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMapType([NotNull] bhlParser.MapTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.mapType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMapType([NotNull] bhlParser.MapTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.explist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExplist([NotNull] bhlParser.ExplistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.explist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExplist([NotNull] bhlParser.ExplistContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpJsonArr</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpJsonArr([NotNull] bhlParser.ExpJsonArrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpJsonArr</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpJsonArr([NotNull] bhlParser.ExpJsonArrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpTypeof</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpTypeof([NotNull] bhlParser.ExpTypeofContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpTypeof</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpTypeof([NotNull] bhlParser.ExpTypeofContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpIs</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpIs([NotNull] bhlParser.ExpIsContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpIs</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpIs([NotNull] bhlParser.ExpIsContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpOr</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpOr([NotNull] bhlParser.ExpOrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpOr</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpOr([NotNull] bhlParser.ExpOrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpLiteralFalse</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpLiteralFalse([NotNull] bhlParser.ExpLiteralFalseContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpLiteralFalse</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpLiteralFalse([NotNull] bhlParser.ExpLiteralFalseContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpLiteralNum</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpLiteralNum([NotNull] bhlParser.ExpLiteralNumContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpLiteralNum</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpLiteralNum([NotNull] bhlParser.ExpLiteralNumContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpCall</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpCall([NotNull] bhlParser.ExpCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpCall</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpCall([NotNull] bhlParser.ExpCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpMulDivMod</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpMulDivMod([NotNull] bhlParser.ExpMulDivModContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpMulDivMod</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpMulDivMod([NotNull] bhlParser.ExpMulDivModContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpCompare</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpCompare([NotNull] bhlParser.ExpCompareContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpCompare</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpCompare([NotNull] bhlParser.ExpCompareContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpAs</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpAs([NotNull] bhlParser.ExpAsContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpAs</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpAs([NotNull] bhlParser.ExpAsContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpLiteralStr</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpLiteralStr([NotNull] bhlParser.ExpLiteralStrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpLiteralStr</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpLiteralStr([NotNull] bhlParser.ExpLiteralStrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpLiteralTrue</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpLiteralTrue([NotNull] bhlParser.ExpLiteralTrueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpLiteralTrue</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpLiteralTrue([NotNull] bhlParser.ExpLiteralTrueContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpJsonObj</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpJsonObj([NotNull] bhlParser.ExpJsonObjContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpJsonObj</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpJsonObj([NotNull] bhlParser.ExpJsonObjContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpUnary</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpUnary([NotNull] bhlParser.ExpUnaryContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpUnary</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpUnary([NotNull] bhlParser.ExpUnaryContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpNew</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpNew([NotNull] bhlParser.ExpNewContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpNew</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpNew([NotNull] bhlParser.ExpNewContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpAddSub</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpAddSub([NotNull] bhlParser.ExpAddSubContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpAddSub</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpAddSub([NotNull] bhlParser.ExpAddSubContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpBitAnd</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpBitAnd([NotNull] bhlParser.ExpBitAndContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpBitAnd</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpBitAnd([NotNull] bhlParser.ExpBitAndContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpLiteralNull</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpLiteralNull([NotNull] bhlParser.ExpLiteralNullContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpLiteralNull</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpLiteralNull([NotNull] bhlParser.ExpLiteralNullContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpTypeCast</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpTypeCast([NotNull] bhlParser.ExpTypeCastContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpTypeCast</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpTypeCast([NotNull] bhlParser.ExpTypeCastContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpTernaryIf</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpTernaryIf([NotNull] bhlParser.ExpTernaryIfContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpTernaryIf</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpTernaryIf([NotNull] bhlParser.ExpTernaryIfContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpLambda</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpLambda([NotNull] bhlParser.ExpLambdaContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpLambda</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpLambda([NotNull] bhlParser.ExpLambdaContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpAnd</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpAnd([NotNull] bhlParser.ExpAndContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpAnd</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpAnd([NotNull] bhlParser.ExpAndContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpBitOr</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpBitOr([NotNull] bhlParser.ExpBitOrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpBitOr</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpBitOr([NotNull] bhlParser.ExpBitOrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpParen</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpParen([NotNull] bhlParser.ExpParenContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpParen</c>
	/// labeled alternative in <see cref="bhlParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpParen([NotNull] bhlParser.ExpParenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.ternaryIfExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTernaryIfExp([NotNull] bhlParser.TernaryIfExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.ternaryIfExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTernaryIfExp([NotNull] bhlParser.TernaryIfExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.newExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNewExp([NotNull] bhlParser.NewExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.newExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNewExp([NotNull] bhlParser.NewExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.foreachExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForeachExp([NotNull] bhlParser.ForeachExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.foreachExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForeachExp([NotNull] bhlParser.ForeachExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.forStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForStmt([NotNull] bhlParser.ForStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.forStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForStmt([NotNull] bhlParser.ForStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.forStmts"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForStmts([NotNull] bhlParser.ForStmtsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.forStmts"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForStmts([NotNull] bhlParser.ForStmtsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.forPre"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForPre([NotNull] bhlParser.ForPreContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.forPre"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForPre([NotNull] bhlParser.ForPreContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.forCond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForCond([NotNull] bhlParser.ForCondContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.forCond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForCond([NotNull] bhlParser.ForCondContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.forPostIter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForPostIter([NotNull] bhlParser.ForPostIterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.forPostIter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForPostIter([NotNull] bhlParser.ForPostIterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.forExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForExp([NotNull] bhlParser.ForExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.forExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForExp([NotNull] bhlParser.ForExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.varDeclareAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarDeclareAssign([NotNull] bhlParser.VarDeclareAssignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.varDeclareAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarDeclareAssign([NotNull] bhlParser.VarDeclareAssignContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.callPostIncDec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCallPostIncDec([NotNull] bhlParser.CallPostIncDecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.callPostIncDec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCallPostIncDec([NotNull] bhlParser.CallPostIncDecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.incrementOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncrementOperator([NotNull] bhlParser.IncrementOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.incrementOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncrementOperator([NotNull] bhlParser.IncrementOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.decrementOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDecrementOperator([NotNull] bhlParser.DecrementOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.decrementOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDecrementOperator([NotNull] bhlParser.DecrementOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LambdaCall</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambdaCall([NotNull] bhlParser.LambdaCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LambdaCall</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambdaCall([NotNull] bhlParser.LambdaCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>DeclAssign</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclAssign([NotNull] bhlParser.DeclAssignContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>DeclAssign</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclAssign([NotNull] bhlParser.DeclAssignContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>VarDecl</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarDecl([NotNull] bhlParser.VarDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>VarDecl</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarDecl([NotNull] bhlParser.VarDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>VarPostOpAssign</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarPostOpAssign([NotNull] bhlParser.VarPostOpAssignContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>VarPostOpAssign</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarPostOpAssign([NotNull] bhlParser.VarPostOpAssignContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>VarPostIncDec</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarPostIncDec([NotNull] bhlParser.VarPostIncDecContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>VarPostIncDec</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarPostIncDec([NotNull] bhlParser.VarPostIncDecContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SymbCall</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSymbCall([NotNull] bhlParser.SymbCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SymbCall</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSymbCall([NotNull] bhlParser.SymbCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>If</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIf([NotNull] bhlParser.IfContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>If</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIf([NotNull] bhlParser.IfContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>While</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhile([NotNull] bhlParser.WhileContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>While</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhile([NotNull] bhlParser.WhileContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>DoWhile</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDoWhile([NotNull] bhlParser.DoWhileContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>DoWhile</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDoWhile([NotNull] bhlParser.DoWhileContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>For</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFor([NotNull] bhlParser.ForContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>For</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFor([NotNull] bhlParser.ForContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Foreach</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForeach([NotNull] bhlParser.ForeachContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Foreach</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForeach([NotNull] bhlParser.ForeachContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Yield</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterYield([NotNull] bhlParser.YieldContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Yield</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitYield([NotNull] bhlParser.YieldContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>YieldWhile</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterYieldWhile([NotNull] bhlParser.YieldWhileContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>YieldWhile</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitYieldWhile([NotNull] bhlParser.YieldWhileContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Break</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBreak([NotNull] bhlParser.BreakContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Break</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBreak([NotNull] bhlParser.BreakContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Continue</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContinue([NotNull] bhlParser.ContinueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Continue</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContinue([NotNull] bhlParser.ContinueContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Return</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturn([NotNull] bhlParser.ReturnContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Return</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturn([NotNull] bhlParser.ReturnContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Paral</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParal([NotNull] bhlParser.ParalContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Paral</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParal([NotNull] bhlParser.ParalContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ParalAll</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParalAll([NotNull] bhlParser.ParalAllContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ParalAll</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParalAll([NotNull] bhlParser.ParalAllContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Defer</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefer([NotNull] bhlParser.DeferContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Defer</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefer([NotNull] bhlParser.DeferContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>BlockNested</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockNested([NotNull] bhlParser.BlockNestedContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BlockNested</c>
	/// labeled alternative in <see cref="bhlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockNested([NotNull] bhlParser.BlockNestedContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.mainIf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMainIf([NotNull] bhlParser.MainIfContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.mainIf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMainIf([NotNull] bhlParser.MainIfContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.elseIf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseIf([NotNull] bhlParser.ElseIfContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.elseIf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseIf([NotNull] bhlParser.ElseIfContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElse([NotNull] bhlParser.ElseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElse([NotNull] bhlParser.ElseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.callExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCallExp([NotNull] bhlParser.CallExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.callExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCallExp([NotNull] bhlParser.CallExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.chainExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChainExp([NotNull] bhlParser.ChainExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.chainExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChainExp([NotNull] bhlParser.ChainExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.typeof"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeof([NotNull] bhlParser.TypeofContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.typeof"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeof([NotNull] bhlParser.TypeofContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.arrAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrAccess([NotNull] bhlParser.ArrAccessContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.arrAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrAccess([NotNull] bhlParser.ArrAccessContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.memberAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberAccess([NotNull] bhlParser.MemberAccessContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.memberAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberAccess([NotNull] bhlParser.MemberAccessContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.callArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCallArgs([NotNull] bhlParser.CallArgsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.callArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCallArgs([NotNull] bhlParser.CallArgsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.callArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCallArg([NotNull] bhlParser.CallArgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.callArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCallArg([NotNull] bhlParser.CallArgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] bhlParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] bhlParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.extensions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExtensions([NotNull] bhlParser.ExtensionsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.extensions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExtensions([NotNull] bhlParser.ExtensionsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.nsDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNsDecl([NotNull] bhlParser.NsDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.nsDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNsDecl([NotNull] bhlParser.NsDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.classDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassDecl([NotNull] bhlParser.ClassDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.classDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassDecl([NotNull] bhlParser.ClassDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.classBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassBlock([NotNull] bhlParser.ClassBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.classBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassBlock([NotNull] bhlParser.ClassBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.classMembers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassMembers([NotNull] bhlParser.ClassMembersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.classMembers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassMembers([NotNull] bhlParser.ClassMembersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.classMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassMember([NotNull] bhlParser.ClassMemberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.classMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassMember([NotNull] bhlParser.ClassMemberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.interfaceDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInterfaceDecl([NotNull] bhlParser.InterfaceDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.interfaceDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInterfaceDecl([NotNull] bhlParser.InterfaceDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.interfaceBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInterfaceBlock([NotNull] bhlParser.InterfaceBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.interfaceBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInterfaceBlock([NotNull] bhlParser.InterfaceBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.interfaceMembers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInterfaceMembers([NotNull] bhlParser.InterfaceMembersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.interfaceMembers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInterfaceMembers([NotNull] bhlParser.InterfaceMembersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.interfaceMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInterfaceMember([NotNull] bhlParser.InterfaceMemberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.interfaceMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInterfaceMember([NotNull] bhlParser.InterfaceMemberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.enumDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumDecl([NotNull] bhlParser.EnumDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.enumDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumDecl([NotNull] bhlParser.EnumDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.enumBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumBlock([NotNull] bhlParser.EnumBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.enumBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumBlock([NotNull] bhlParser.EnumBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.enumMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumMember([NotNull] bhlParser.EnumMemberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.enumMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumMember([NotNull] bhlParser.EnumMemberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.virtualFlag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVirtualFlag([NotNull] bhlParser.VirtualFlagContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.virtualFlag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVirtualFlag([NotNull] bhlParser.VirtualFlagContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.overrideFlag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOverrideFlag([NotNull] bhlParser.OverrideFlagContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.overrideFlag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOverrideFlag([NotNull] bhlParser.OverrideFlagContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.funcFlags"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncFlags([NotNull] bhlParser.FuncFlagsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.funcFlags"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncFlags([NotNull] bhlParser.FuncFlagsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.funcDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncDecl([NotNull] bhlParser.FuncDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.funcDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncDecl([NotNull] bhlParser.FuncDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.funcType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncType([NotNull] bhlParser.FuncTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.funcType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncType([NotNull] bhlParser.FuncTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.funcBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncBlock([NotNull] bhlParser.FuncBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.funcBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncBlock([NotNull] bhlParser.FuncBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.interfaceFuncDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInterfaceFuncDecl([NotNull] bhlParser.InterfaceFuncDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.interfaceFuncDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInterfaceFuncDecl([NotNull] bhlParser.InterfaceFuncDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.funcLambda"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncLambda([NotNull] bhlParser.FuncLambdaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.funcLambda"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncLambda([NotNull] bhlParser.FuncLambdaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.refType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRefType([NotNull] bhlParser.RefTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.refType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRefType([NotNull] bhlParser.RefTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.retType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRetType([NotNull] bhlParser.RetTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.retType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRetType([NotNull] bhlParser.RetTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.types"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypes([NotNull] bhlParser.TypesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.types"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypes([NotNull] bhlParser.TypesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.funcParams"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncParams([NotNull] bhlParser.FuncParamsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.funcParams"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncParams([NotNull] bhlParser.FuncParamsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.funcParamDeclare"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncParamDeclare([NotNull] bhlParser.FuncParamDeclareContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.funcParamDeclare"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncParamDeclare([NotNull] bhlParser.FuncParamDeclareContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.varsDeclare"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarsDeclare([NotNull] bhlParser.VarsDeclareContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.varsDeclare"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarsDeclare([NotNull] bhlParser.VarsDeclareContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.varDeclare"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarDeclare([NotNull] bhlParser.VarDeclareContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.varDeclare"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarDeclare([NotNull] bhlParser.VarDeclareContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.varOrDeclare"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarOrDeclare([NotNull] bhlParser.VarOrDeclareContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.varOrDeclare"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarOrDeclare([NotNull] bhlParser.VarOrDeclareContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.varOrDeclares"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarOrDeclares([NotNull] bhlParser.VarOrDeclaresContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.varOrDeclares"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarOrDeclares([NotNull] bhlParser.VarOrDeclaresContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.varsDeclareOrCallExps"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarsDeclareOrCallExps([NotNull] bhlParser.VarsDeclareOrCallExpsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.varsDeclareOrCallExps"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarsDeclareOrCallExps([NotNull] bhlParser.VarsDeclareOrCallExpsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.varDeclareOrCallExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarDeclareOrCallExp([NotNull] bhlParser.VarDeclareOrCallExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.varDeclareOrCallExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarDeclareOrCallExp([NotNull] bhlParser.VarDeclareOrCallExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.assignExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignExp([NotNull] bhlParser.AssignExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.assignExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignExp([NotNull] bhlParser.AssignExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.operatorOr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorOr([NotNull] bhlParser.OperatorOrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.operatorOr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorOr([NotNull] bhlParser.OperatorOrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.operatorAnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorAnd([NotNull] bhlParser.OperatorAndContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.operatorAnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorAnd([NotNull] bhlParser.OperatorAndContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.operatorBitOr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorBitOr([NotNull] bhlParser.OperatorBitOrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.operatorBitOr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorBitOr([NotNull] bhlParser.OperatorBitOrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.operatorBitAnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorBitAnd([NotNull] bhlParser.OperatorBitAndContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.operatorBitAnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorBitAnd([NotNull] bhlParser.OperatorBitAndContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.operatorPostOpAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorPostOpAssign([NotNull] bhlParser.OperatorPostOpAssignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.operatorPostOpAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorPostOpAssign([NotNull] bhlParser.OperatorPostOpAssignContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.operatorComparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorComparison([NotNull] bhlParser.OperatorComparisonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.operatorComparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorComparison([NotNull] bhlParser.OperatorComparisonContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.operatorAddSub"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorAddSub([NotNull] bhlParser.OperatorAddSubContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.operatorAddSub"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorAddSub([NotNull] bhlParser.OperatorAddSubContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.operatorMulDivMod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorMulDivMod([NotNull] bhlParser.OperatorMulDivModContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.operatorMulDivMod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorMulDivMod([NotNull] bhlParser.OperatorMulDivModContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.operatorUnary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorUnary([NotNull] bhlParser.OperatorUnaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.operatorUnary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorUnary([NotNull] bhlParser.OperatorUnaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.isRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIsRef([NotNull] bhlParser.IsRefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.isRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIsRef([NotNull] bhlParser.IsRefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber([NotNull] bhlParser.NumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber([NotNull] bhlParser.NumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString([NotNull] bhlParser.StringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString([NotNull] bhlParser.StringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.jsonObject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJsonObject([NotNull] bhlParser.JsonObjectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.jsonObject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJsonObject([NotNull] bhlParser.JsonObjectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.jsonEmptyObj"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJsonEmptyObj([NotNull] bhlParser.JsonEmptyObjContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.jsonEmptyObj"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJsonEmptyObj([NotNull] bhlParser.JsonEmptyObjContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.jsonPair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJsonPair([NotNull] bhlParser.JsonPairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.jsonPair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJsonPair([NotNull] bhlParser.JsonPairContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.jsonArray"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJsonArray([NotNull] bhlParser.JsonArrayContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.jsonArray"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJsonArray([NotNull] bhlParser.JsonArrayContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.jsonEmptyArr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJsonEmptyArr([NotNull] bhlParser.JsonEmptyArrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.jsonEmptyArr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJsonEmptyArr([NotNull] bhlParser.JsonEmptyArrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bhlParser.jsonValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJsonValue([NotNull] bhlParser.JsonValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bhlParser.jsonValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJsonValue([NotNull] bhlParser.JsonValueContext context);
}
