//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from bhlPreprocLexer.g by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class bhlPreprocLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		SHARP=1, CODE=2, IF=3, ELSE=4, ENDIF=5, BANG=6, DIRECTIVE_WHITESPACES=7, 
		DIRECTIVE_STRING=8, CONDITIONAL_SYMBOL=9, NEW_LINE=10, DIRECTIVE_COMMENT=11, 
		SLASH=12;
	public const int
		COMMENTS_CHANNEL=2;
	public const int
		DIRECTIVE_MODE=1;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN", "COMMENTS_CHANNEL"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE", "DIRECTIVE_MODE"
	};

	public static readonly string[] ruleNames = {
		"SHARP", "COMMENT", "LINE_COMMENT", "SLASH", "CHARACTER_LITERAL", "QUOTE_STRING", 
		"STRING", "CODE", "IF", "ELSE", "ENDIF", "BANG", "DIRECTIVE_WHITESPACES", 
		"DIRECTIVE_STRING", "CONDITIONAL_SYMBOL", "NEW_LINE", "DIRECTIVE_COMMENT", 
		"EscapeSequence", "OctalEscape", "UnicodeEscape", "HexDigit", "StringFragment", 
		"LETTER"
	};


	public bhlPreprocLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public bhlPreprocLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'#'", null, "'if'", "'else'", "'endif'", "'!'", null, null, null, 
		null, null, "'/'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "SHARP", "CODE", "IF", "ELSE", "ENDIF", "BANG", "DIRECTIVE_WHITESPACES", 
		"DIRECTIVE_STRING", "CONDITIONAL_SYMBOL", "NEW_LINE", "DIRECTIVE_COMMENT", 
		"SLASH"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "bhlPreprocLexer.g"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static bhlPreprocLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\xE', '\xD3', '\b', '\x1', '\b', '\x1', '\x4', '\x2', 
		'\t', '\x2', '\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', 
		'\x5', '\t', '\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', 
		'\x4', '\b', '\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', 
		'\x4', '\v', '\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', 
		'\x4', '\xE', '\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', 
		'\x10', '\x4', '\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', 
		'\x13', '\t', '\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', 
		'\x15', '\x4', '\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', 
		'\x18', '\t', '\x18', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\a', '\x3', 
		';', '\n', '\x3', '\f', '\x3', '\xE', '\x3', '>', '\v', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\a', '\x4', 'I', '\n', 
		'\x4', '\f', '\x4', '\xE', '\x4', 'L', '\v', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x5', '\x6', 'W', '\n', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\a', '\a', '`', '\n', '\a', '\f', '\a', '\xE', '\a', '\x63', 
		'\v', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x6', '\t', 
		'n', '\n', '\t', '\r', '\t', '\xE', '\t', 'o', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x6', '\xE', '\x83', 
		'\n', '\xE', '\r', '\xE', '\xE', '\xE', '\x84', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\a', '\x10', '\x8E', '\n', '\x10', '\f', '\x10', '\xE', '\x10', '\x91', 
		'\v', '\x10', '\x3', '\x11', '\x5', '\x11', '\x94', '\n', '\x11', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\a', '\x12', '\x9E', '\n', '\x12', 
		'\f', '\x12', '\xE', '\x12', '\xA1', '\v', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', 
		'\x13', '\x3', '\x13', '\x3', '\x13', '\x5', '\x13', '\xAC', '\n', '\x13', 
		'\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', 
		'\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x5', '\x14', 
		'\xB7', '\n', '\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', 
		'\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x3', 
		'\x16', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\a', 
		'\x17', '\xC6', '\n', '\x17', '\f', '\x17', '\xE', '\x17', '\xC9', '\v', 
		'\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x18', '\x3', '\x18', '\x3', 
		'\x18', '\x3', '\x18', '\x3', '\x18', '\x5', '\x18', '\xD2', '\n', '\x18', 
		'\x4', '<', '\x9F', '\x2', '\x19', '\x4', '\x3', '\x6', '\x2', '\b', '\x2', 
		'\n', '\xE', '\f', '\x2', '\xE', '\x2', '\x10', '\x2', '\x12', '\x4', 
		'\x14', '\x5', '\x16', '\x6', '\x18', '\a', '\x1A', '\b', '\x1C', '\t', 
		'\x1E', '\n', ' ', '\v', '\"', '\f', '$', '\r', '&', '\x2', '(', '\x2', 
		'*', '\x2', ',', '\x2', '.', '\x2', '\x30', '\x2', '\x4', '\x2', '\x3', 
		'\x11', '\x4', '\x2', '\f', '\f', '\xF', '\xF', '\x4', '\x2', ')', ')', 
		'^', '^', '\x5', '\x2', '$', '%', ')', ')', '\x31', '\x31', '\x4', '\x2', 
		'\v', '\v', '\"', '\"', '\x3', '\x2', '\x32', ';', '\n', '\x2', '$', '$', 
		')', ')', '^', '^', '\x64', '\x64', 'h', 'h', 'p', 'p', 't', 't', 'v', 
		'v', '\x3', '\x2', '\x32', '\x35', '\x3', '\x2', '\x32', '\x39', '\x5', 
		'\x2', '\x32', ';', '\x43', 'H', '\x63', 'h', '\x4', '\x2', '$', '$', 
		'^', '^', '\x6', '\x2', '&', '&', '\x43', '\\', '\x61', '\x61', '\x63', 
		'|', '\x4', '\x2', '\x2', '\x101', '\xD802', '\xDC01', '\x3', '\x2', '\xD802', 
		'\xDC01', '\x3', '\x2', '\xDC02', '\xE001', '\x3', '\x2', '\xEB', '\xEB', 
		'\x2', '\xDF', '\x2', '\x4', '\x3', '\x2', '\x2', '\x2', '\x2', '\x6', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\b', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\n', '\x3', '\x2', '\x2', '\x2', '\x2', '\f', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\xE', '\x3', '\x2', '\x2', '\x2', '\x2', '\x10', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x12', '\x3', '\x2', '\x2', '\x2', '\x3', '\x14', 
		'\x3', '\x2', '\x2', '\x2', '\x3', '\x16', '\x3', '\x2', '\x2', '\x2', 
		'\x3', '\x18', '\x3', '\x2', '\x2', '\x2', '\x3', '\x1A', '\x3', '\x2', 
		'\x2', '\x2', '\x3', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x3', '\x1E', 
		'\x3', '\x2', '\x2', '\x2', '\x3', ' ', '\x3', '\x2', '\x2', '\x2', '\x3', 
		'\"', '\x3', '\x2', '\x2', '\x2', '\x3', '$', '\x3', '\x2', '\x2', '\x2', 
		'\x4', '\x32', '\x3', '\x2', '\x2', '\x2', '\x6', '\x36', '\x3', '\x2', 
		'\x2', '\x2', '\b', '\x44', '\x3', '\x2', '\x2', '\x2', '\n', 'O', '\x3', 
		'\x2', '\x2', '\x2', '\f', 'S', '\x3', '\x2', '\x2', '\x2', '\xE', '\\', 
		'\x3', '\x2', '\x2', '\x2', '\x10', 'h', '\x3', '\x2', '\x2', '\x2', '\x12', 
		'm', '\x3', '\x2', '\x2', '\x2', '\x14', 'q', '\x3', '\x2', '\x2', '\x2', 
		'\x16', 't', '\x3', '\x2', '\x2', '\x2', '\x18', 'y', '\x3', '\x2', '\x2', 
		'\x2', '\x1A', '\x7F', '\x3', '\x2', '\x2', '\x2', '\x1C', '\x82', '\x3', 
		'\x2', '\x2', '\x2', '\x1E', '\x88', '\x3', '\x2', '\x2', '\x2', ' ', 
		'\x8A', '\x3', '\x2', '\x2', '\x2', '\"', '\x93', '\x3', '\x2', '\x2', 
		'\x2', '$', '\x99', '\x3', '\x2', '\x2', '\x2', '&', '\xAB', '\x3', '\x2', 
		'\x2', '\x2', '(', '\xB6', '\x3', '\x2', '\x2', '\x2', '*', '\xB8', '\x3', 
		'\x2', '\x2', '\x2', ',', '\xBF', '\x3', '\x2', '\x2', '\x2', '.', '\xC1', 
		'\x3', '\x2', '\x2', '\x2', '\x30', '\xD1', '\x3', '\x2', '\x2', '\x2', 
		'\x32', '\x33', '\a', '%', '\x2', '\x2', '\x33', '\x34', '\x3', '\x2', 
		'\x2', '\x2', '\x34', '\x35', '\b', '\x2', '\x2', '\x2', '\x35', '\x5', 
		'\x3', '\x2', '\x2', '\x2', '\x36', '\x37', '\a', '\x31', '\x2', '\x2', 
		'\x37', '\x38', '\a', ',', '\x2', '\x2', '\x38', '<', '\x3', '\x2', '\x2', 
		'\x2', '\x39', ';', '\v', '\x2', '\x2', '\x2', ':', '\x39', '\x3', '\x2', 
		'\x2', '\x2', ';', '>', '\x3', '\x2', '\x2', '\x2', '<', '=', '\x3', '\x2', 
		'\x2', '\x2', '<', ':', '\x3', '\x2', '\x2', '\x2', '=', '?', '\x3', '\x2', 
		'\x2', '\x2', '>', '<', '\x3', '\x2', '\x2', '\x2', '?', '@', '\a', ',', 
		'\x2', '\x2', '@', '\x41', '\a', '\x31', '\x2', '\x2', '\x41', '\x42', 
		'\x3', '\x2', '\x2', '\x2', '\x42', '\x43', '\b', '\x3', '\x3', '\x2', 
		'\x43', '\a', '\x3', '\x2', '\x2', '\x2', '\x44', '\x45', '\a', '\x31', 
		'\x2', '\x2', '\x45', '\x46', '\a', '\x31', '\x2', '\x2', '\x46', 'J', 
		'\x3', '\x2', '\x2', '\x2', 'G', 'I', '\n', '\x2', '\x2', '\x2', 'H', 
		'G', '\x3', '\x2', '\x2', '\x2', 'I', 'L', '\x3', '\x2', '\x2', '\x2', 
		'J', 'H', '\x3', '\x2', '\x2', '\x2', 'J', 'K', '\x3', '\x2', '\x2', '\x2', 
		'K', 'M', '\x3', '\x2', '\x2', '\x2', 'L', 'J', '\x3', '\x2', '\x2', '\x2', 
		'M', 'N', '\b', '\x4', '\x3', '\x2', 'N', '\t', '\x3', '\x2', '\x2', '\x2', 
		'O', 'P', '\a', '\x31', '\x2', '\x2', 'P', 'Q', '\x3', '\x2', '\x2', '\x2', 
		'Q', 'R', '\b', '\x5', '\x3', '\x2', 'R', '\v', '\x3', '\x2', '\x2', '\x2', 
		'S', 'V', '\a', ')', '\x2', '\x2', 'T', 'W', '\x5', '&', '\x13', '\x2', 
		'U', 'W', '\n', '\x3', '\x2', '\x2', 'V', 'T', '\x3', '\x2', '\x2', '\x2', 
		'V', 'U', '\x3', '\x2', '\x2', '\x2', 'W', 'X', '\x3', '\x2', '\x2', '\x2', 
		'X', 'Y', '\a', ')', '\x2', '\x2', 'Y', 'Z', '\x3', '\x2', '\x2', '\x2', 
		'Z', '[', '\b', '\x6', '\x3', '\x2', '[', '\r', '\x3', '\x2', '\x2', '\x2', 
		'\\', '\x61', '\a', ')', '\x2', '\x2', ']', '`', '\x5', '&', '\x13', '\x2', 
		'^', '`', '\n', '\x3', '\x2', '\x2', '_', ']', '\x3', '\x2', '\x2', '\x2', 
		'_', '^', '\x3', '\x2', '\x2', '\x2', '`', '\x63', '\x3', '\x2', '\x2', 
		'\x2', '\x61', '_', '\x3', '\x2', '\x2', '\x2', '\x61', '\x62', '\x3', 
		'\x2', '\x2', '\x2', '\x62', '\x64', '\x3', '\x2', '\x2', '\x2', '\x63', 
		'\x61', '\x3', '\x2', '\x2', '\x2', '\x64', '\x65', '\a', ')', '\x2', 
		'\x2', '\x65', '\x66', '\x3', '\x2', '\x2', '\x2', '\x66', 'g', '\b', 
		'\a', '\x3', '\x2', 'g', '\xF', '\x3', '\x2', '\x2', '\x2', 'h', 'i', 
		'\x5', '.', '\x17', '\x2', 'i', 'j', '\x3', '\x2', '\x2', '\x2', 'j', 
		'k', '\b', '\b', '\x3', '\x2', 'k', '\x11', '\x3', '\x2', '\x2', '\x2', 
		'l', 'n', '\n', '\x4', '\x2', '\x2', 'm', 'l', '\x3', '\x2', '\x2', '\x2', 
		'n', 'o', '\x3', '\x2', '\x2', '\x2', 'o', 'm', '\x3', '\x2', '\x2', '\x2', 
		'o', 'p', '\x3', '\x2', '\x2', '\x2', 'p', '\x13', '\x3', '\x2', '\x2', 
		'\x2', 'q', 'r', '\a', 'k', '\x2', '\x2', 'r', 's', '\a', 'h', '\x2', 
		'\x2', 's', '\x15', '\x3', '\x2', '\x2', '\x2', 't', 'u', '\a', 'g', '\x2', 
		'\x2', 'u', 'v', '\a', 'n', '\x2', '\x2', 'v', 'w', '\a', 'u', '\x2', 
		'\x2', 'w', 'x', '\a', 'g', '\x2', '\x2', 'x', '\x17', '\x3', '\x2', '\x2', 
		'\x2', 'y', 'z', '\a', 'g', '\x2', '\x2', 'z', '{', '\a', 'p', '\x2', 
		'\x2', '{', '|', '\a', '\x66', '\x2', '\x2', '|', '}', '\a', 'k', '\x2', 
		'\x2', '}', '~', '\a', 'h', '\x2', '\x2', '~', '\x19', '\x3', '\x2', '\x2', 
		'\x2', '\x7F', '\x80', '\a', '#', '\x2', '\x2', '\x80', '\x1B', '\x3', 
		'\x2', '\x2', '\x2', '\x81', '\x83', '\t', '\x5', '\x2', '\x2', '\x82', 
		'\x81', '\x3', '\x2', '\x2', '\x2', '\x83', '\x84', '\x3', '\x2', '\x2', 
		'\x2', '\x84', '\x82', '\x3', '\x2', '\x2', '\x2', '\x84', '\x85', '\x3', 
		'\x2', '\x2', '\x2', '\x85', '\x86', '\x3', '\x2', '\x2', '\x2', '\x86', 
		'\x87', '\b', '\xE', '\x4', '\x2', '\x87', '\x1D', '\x3', '\x2', '\x2', 
		'\x2', '\x88', '\x89', '\x5', '.', '\x17', '\x2', '\x89', '\x1F', '\x3', 
		'\x2', '\x2', '\x2', '\x8A', '\x8F', '\x5', '\x30', '\x18', '\x2', '\x8B', 
		'\x8E', '\x5', '\x30', '\x18', '\x2', '\x8C', '\x8E', '\t', '\x6', '\x2', 
		'\x2', '\x8D', '\x8B', '\x3', '\x2', '\x2', '\x2', '\x8D', '\x8C', '\x3', 
		'\x2', '\x2', '\x2', '\x8E', '\x91', '\x3', '\x2', '\x2', '\x2', '\x8F', 
		'\x8D', '\x3', '\x2', '\x2', '\x2', '\x8F', '\x90', '\x3', '\x2', '\x2', 
		'\x2', '\x90', '!', '\x3', '\x2', '\x2', '\x2', '\x91', '\x8F', '\x3', 
		'\x2', '\x2', '\x2', '\x92', '\x94', '\a', '\xF', '\x2', '\x2', '\x93', 
		'\x92', '\x3', '\x2', '\x2', '\x2', '\x93', '\x94', '\x3', '\x2', '\x2', 
		'\x2', '\x94', '\x95', '\x3', '\x2', '\x2', '\x2', '\x95', '\x96', '\a', 
		'\f', '\x2', '\x2', '\x96', '\x97', '\x3', '\x2', '\x2', '\x2', '\x97', 
		'\x98', '\b', '\x11', '\x5', '\x2', '\x98', '#', '\x3', '\x2', '\x2', 
		'\x2', '\x99', '\x9A', '\a', '\x31', '\x2', '\x2', '\x9A', '\x9B', '\a', 
		',', '\x2', '\x2', '\x9B', '\x9F', '\x3', '\x2', '\x2', '\x2', '\x9C', 
		'\x9E', '\v', '\x2', '\x2', '\x2', '\x9D', '\x9C', '\x3', '\x2', '\x2', 
		'\x2', '\x9E', '\xA1', '\x3', '\x2', '\x2', '\x2', '\x9F', '\xA0', '\x3', 
		'\x2', '\x2', '\x2', '\x9F', '\x9D', '\x3', '\x2', '\x2', '\x2', '\xA0', 
		'\xA2', '\x3', '\x2', '\x2', '\x2', '\xA1', '\x9F', '\x3', '\x2', '\x2', 
		'\x2', '\xA2', '\xA3', '\a', ',', '\x2', '\x2', '\xA3', '\xA4', '\a', 
		'\x31', '\x2', '\x2', '\xA4', '\xA5', '\x3', '\x2', '\x2', '\x2', '\xA5', 
		'\xA6', '\b', '\x12', '\x6', '\x2', '\xA6', '%', '\x3', '\x2', '\x2', 
		'\x2', '\xA7', '\xA8', '\a', '^', '\x2', '\x2', '\xA8', '\xAC', '\t', 
		'\a', '\x2', '\x2', '\xA9', '\xAC', '\x5', '(', '\x14', '\x2', '\xAA', 
		'\xAC', '\x5', '*', '\x15', '\x2', '\xAB', '\xA7', '\x3', '\x2', '\x2', 
		'\x2', '\xAB', '\xA9', '\x3', '\x2', '\x2', '\x2', '\xAB', '\xAA', '\x3', 
		'\x2', '\x2', '\x2', '\xAC', '\'', '\x3', '\x2', '\x2', '\x2', '\xAD', 
		'\xAE', '\a', '^', '\x2', '\x2', '\xAE', '\xAF', '\t', '\b', '\x2', '\x2', 
		'\xAF', '\xB0', '\t', '\t', '\x2', '\x2', '\xB0', '\xB7', '\t', '\t', 
		'\x2', '\x2', '\xB1', '\xB2', '\a', '^', '\x2', '\x2', '\xB2', '\xB3', 
		'\t', '\t', '\x2', '\x2', '\xB3', '\xB7', '\t', '\t', '\x2', '\x2', '\xB4', 
		'\xB5', '\a', '^', '\x2', '\x2', '\xB5', '\xB7', '\t', '\t', '\x2', '\x2', 
		'\xB6', '\xAD', '\x3', '\x2', '\x2', '\x2', '\xB6', '\xB1', '\x3', '\x2', 
		'\x2', '\x2', '\xB6', '\xB4', '\x3', '\x2', '\x2', '\x2', '\xB7', ')', 
		'\x3', '\x2', '\x2', '\x2', '\xB8', '\xB9', '\a', '^', '\x2', '\x2', '\xB9', 
		'\xBA', '\a', 'w', '\x2', '\x2', '\xBA', '\xBB', '\x5', ',', '\x16', '\x2', 
		'\xBB', '\xBC', '\x5', ',', '\x16', '\x2', '\xBC', '\xBD', '\x5', ',', 
		'\x16', '\x2', '\xBD', '\xBE', '\x5', ',', '\x16', '\x2', '\xBE', '+', 
		'\x3', '\x2', '\x2', '\x2', '\xBF', '\xC0', '\t', '\n', '\x2', '\x2', 
		'\xC0', '-', '\x3', '\x2', '\x2', '\x2', '\xC1', '\xC7', '\a', '$', '\x2', 
		'\x2', '\xC2', '\xC6', '\n', '\v', '\x2', '\x2', '\xC3', '\xC4', '\a', 
		'^', '\x2', '\x2', '\xC4', '\xC6', '\v', '\x2', '\x2', '\x2', '\xC5', 
		'\xC2', '\x3', '\x2', '\x2', '\x2', '\xC5', '\xC3', '\x3', '\x2', '\x2', 
		'\x2', '\xC6', '\xC9', '\x3', '\x2', '\x2', '\x2', '\xC7', '\xC5', '\x3', 
		'\x2', '\x2', '\x2', '\xC7', '\xC8', '\x3', '\x2', '\x2', '\x2', '\xC8', 
		'\xCA', '\x3', '\x2', '\x2', '\x2', '\xC9', '\xC7', '\x3', '\x2', '\x2', 
		'\x2', '\xCA', '\xCB', '\a', '$', '\x2', '\x2', '\xCB', '/', '\x3', '\x2', 
		'\x2', '\x2', '\xCC', '\xD2', '\t', '\f', '\x2', '\x2', '\xCD', '\xD2', 
		'\n', '\r', '\x2', '\x2', '\xCE', '\xCF', '\t', '\xE', '\x2', '\x2', '\xCF', 
		'\xD2', '\t', '\xF', '\x2', '\x2', '\xD0', '\xD2', '\t', '\x10', '\x2', 
		'\x2', '\xD1', '\xCC', '\x3', '\x2', '\x2', '\x2', '\xD1', '\xCD', '\x3', 
		'\x2', '\x2', '\x2', '\xD1', '\xCE', '\x3', '\x2', '\x2', '\x2', '\xD1', 
		'\xD0', '\x3', '\x2', '\x2', '\x2', '\xD2', '\x31', '\x3', '\x2', '\x2', 
		'\x2', '\x14', '\x2', '\x3', '<', 'J', 'V', '_', '\x61', 'o', '\x84', 
		'\x8D', '\x8F', '\x93', '\x9F', '\xAB', '\xB6', '\xC5', '\xC7', '\xD1', 
		'\a', '\x4', '\x3', '\x2', '\t', '\x4', '\x2', '\x2', '\x3', '\x2', '\x4', 
		'\x2', '\x2', '\x2', '\x4', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
