<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>hotreload</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="hotreload.cs" />
    <Compile Include="bindings.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\front\bhl_front.csproj" />
  </ItemGroup>

</Project>
